live_config_reload = true

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 11.0

[font.normal]
family = "UbuntuMono Nerd Font"

[shell]
program = "/usr/bin/fish"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
opacity = 0.95
title = "Alacritty"

[window.class]
general = "alacritty"
instance = "alacritty"

[window.padding]
x = 5
y = 5

# Nord theme "https://github.com/nordtheme/alacritty"

[colors]
cursor.text = "#2e3440"
cursor.cursor = "#d8dee9"
vi_mode_cursor.text = "#2e3440"
vi_mode_cursor.cursor = "#d8dee9"
selection.text = "CellForeground"
selection.background = "#4c566a"

[colors.primary]
background = "#2e3440"
foreground = "#d8dee9"
dim_foreground = "#a5abb6"

[colors.search]
matches.foreground = "CellBackground"
matches.background = "#88c0d0"

[colors.normal]
black = "#3b4252"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#88c0d0"
white = "#e5e9f0"

[colors.bright]
black = "#4c566a"
red = "#bf616a"
green = "#a3be8c"
yellow = "#ebcb8b"
blue = "#81a1c1"
magenta = "#b48ead"
cyan = "#8fbcbb"
white = "#eceff4"

[colors.dim]
black = "#373e4d"
red = "#94545d"
green = "#809575"
yellow = "#b29e75"
blue = "#68809a"
magenta = "#8c738c"
cyan = "#6d96a5"
white = "#aeb3bb"

